User auth ux
ValdasVabolis/Defense-of-the-Trade-League-Locals-Edition pull request #2
Opened 2020-10-06 22:41 UTC by ValdasVabolis

Work in progress.

2020-10-07 08:26 UTC, Boulderis reviewed
Ne hard coding taip, paskui bus sunku atnaujinti. Naudot tag helperius asp-for ir asp-action.
Pavyzdys:
<label asp-for="Email">Email address:</label>
<input asp-for="Email"></input>

2020-10-07 08:26 UTC, Boulderis commented on Support_Your_Locals/Views/Auth/SignUp.cshtml
> +        <form>
Turėtų būt <form asp-action="SignUp" method="post">

2020-10-07 08:27 UTC, Boulderis commented on Support_Your_Locals/wwwroot/css/site.css
>      margin-bottom: 12px;
Šita klasė, kaip suprantu bus naudojama ateityje?

2020-10-07 08:27 UTC, Boulderis commented on Support_Your_Locals/Views/Auth/SignUp.cshtml
> +                <label for="exampleInputPassword1">Password</label>
Su slaptažodžiais dar neskubėk, reikės laiko, kol galėsim juos integruoti backende.

2020-10-07 08:28 UTC, ValdasVabolis commented on Support_Your_Locals/Views/Auth/SignUp.cshtml
> +                <label for="exampleInputPassword1">Password</label>
Taip, čia tik tuščias skeletas kol kas

2020-10-07 08:29 UTC, Boulderis commented on Support_Your_Locals/Views/Auth/SignUp.cshtml
> +            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
Hard coding'as. ASP.NET palaiko tag helperius, kurie palengvina darbą.

2020-10-07 08:29 UTC, ValdasVabolis commented on Support_Your_Locals/wwwroot/css/site.css
>      margin-bottom: 12px;
jeigu navbar-brand, tai čia buvo auto-generated, bet jo bus naudojama ir ateityje

2020-10-07 08:31 UTC, Boulderis commented
Pridėk dar @model Support_Your_Locals.Models.UserRegisterModel SignUp.cshtml viršuje, nes tag helperis nežinos, iš kur imti informaciją.

2020-10-07 10:33 UTC, Yar3k commented
Auth/SignIn should not work for now rigth?

2020-10-08 09:09 UTC, Boulderis requested changes
Kritinių klaidų nėra. Bet prieš merginant reikalingi pakeitimai.

2020-10-08 09:09 UTC, Boulderis commented on Support_Your_Locals/Views/Auth/SignIn.cshtml
> +﻿@model Support_Your_Locals.Models.UserRegisterModel
Darot pagal pavyzdį, o ne pagal logiką: turi būti @model Support_Your_Locals.Models.UserLoginModel

2020-10-08 09:09 UTC, Boulderis commented on Support_Your_Locals/Views/Auth/SignIn.cshtml
> +                <a asp-controller="Auth" asp-action="SignUp">Not a member yet? Sign up</a>
asp-controller="Auth" šiuo atveju nebūtinas, nes jis yra by default.

2020-10-10 10:04 UTC, merged